#!/usr/bin/python3

from urllib.error import URLError
import decorator as dc
import collinsScrap
import spellCheck
import argparse

parser = argparse.ArgumentParser(description="///### COLLINS DICTIONARY ###///")
parser.add_argument("-v", "--version", action="version", version="v1.0")
parser.add_argument("vocab", metavar="word(s)", type=str, nargs="+", help="vocab/phrase")
args = parser.parse_args()


if __name__ == "__main__":
    word = " ".join(args.vocab)
    try:
        word, ret = collinsScrap.query(word)
        if len(ret) == 0:
            print(dc.txtStyle.bold + dc.txtStyle.red31 + "*** No results ***" + dc.txtStyle.reset)
        else: dc.printTxt(word, ret)
    except URLError:
        print(dc.txtStyle.bold + dc.txtStyle.red31 + "*** URLError ***" + dc.txtStyle.reset)
        print(dc.txtStyle.red31 + "Please check your wifi connection" + dc.txtStyle.reset)
    except IndexError:
        pass
    except KeyboardInterrupt:
        print(dc.txtStyle.bold + dc.txtStyle.red31 + "*** KeyboardInterrupt ***" + dc.txtStyle.reset)