#!/usr/bin/python3

from urllib.error import URLError
import decorator as dc
import collinsScrape
import spellCheck
import argparse


VERSION = "v1.0"

description = dc.txtStyle.bold + dc.txtStyle.white + "///### COLLINS DICTIONARY ###///" + dc.txtStyle.reset
parser = argparse.ArgumentParser(description=description)
parser.add_argument("-v", "--version", action="version", version=VERSION)
parser.add_argument("vocab", metavar="vocabulary", type=str, nargs="+", help="word/phrase")
parser.add_argument("-d", "--debug", action="store_true", help="show inside contents for debugging")
args = parser.parse_args()

DEBUG = args.debug
OPTIONS = {"r": "retype your word", "q": "quit"} # spell check options


if __name__ == "__main__":
    word = " ".join(args.vocab)

    dc.printTitle()
    try:
        typo = collinsScrape.query(word, DEBUG)
        while typo:
            word = spellCheck.suggest(word, OPTIONS, DEBUG)
            if word=="q": break
            elif word=="r": word = input("What's your word of interest:\n")
            
            typo = collinsScrape.query(word, DEBUG)
            # print(dc.txtStyle.bold + dc.txtStyle.red31 + "********* No results *********" + dc.txtStyle.reset)

    except URLError:
        print(dc.txtStyle.bold + dc.txtStyle.red31 + "********* URLError *********" + dc.txtStyle.reset)
        print(dc.txtStyle.red31 + "Please check your wifi connection" + dc.txtStyle.reset)

    except KeyboardInterrupt:
        print(dc.txtStyle.bold + dc.txtStyle.red31 + "********* KeyboardInterrupt *********" + dc.txtStyle.reset)